##Loading and processing the data

library(ggplot2)#needed for plots
library(xtable)#needed for pretty table

## Load the the data file
df.1 <- read.csv("activity.csv")

##Check the first 5 rows of data before processing the data for the Porject.
h.noproc <- head(df.1, 5)
h.noproc <- xtable(h.noproc, caption="First 5 rows: non-processed", label="Head Xtable", digits=1)
print(h.noproc, include.rownames = TRUE, caption.placement="top")

##% latex table generated in R 3.1.2 by xtable 1.7-4 package
##% Fri Feb 13 14:14:12 2015

##Cleaning up the data for processing by removing the NA's in the data.
##We can evaluate first five initial rows of data in the df data set after removing na. values.

df <- na.omit(df.1)
h.proc <- head(df, 5)
h.proc <- xtable(h.proc, caption="First 5 rows: processed", label="HeadP Xtable", digits=1)
print(h.proc, include.rownames = TRUE, caption.placement="top")

##% latex table generated in R 3.1.2 by xtable 1.7-4 package
##% Fri Feb 13 14:41:33 2015

##What is mean total number of steps taken per day?
##Histogram of the total number of steps taken each day

df.steps <- aggregate(steps ~ date, df, sum)
##Raw Histogram
hist(df.steps$steps, col="lightblue", main = "Histogram of Total # Steps Taken Each Day", 
     xlab="Total Number of Steps in a Day")
## Histogram of Total number of steps takes was displayed with above steps

#################################################################################

##New Bins set
qplot(steps, data=df.steps, binwidth = "1", xlab = "Total number of steps taken each day", 
      main = "Steps with binwidth set at 1", na.rm=TRUE) + 
  geom_histogram(colour="darkgreen", aes(fill = ..count..)) 
#### stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.

##Steps with binwidth set at 1


## Calculate Mean Total Number of Steps per day
mean(df.steps$steps)

## Result Displayed  --------[1] 10766

## Calculate Median Total Number of Steps per day
median(df.steps$steps)

## Result Displayed  -------[1] 10765

desc <- summary(df.steps) #from the psych library
desc <- xtable(desc, caption="Summary Statistics for Data", 
               label="Description Xtable", digits=1)
print(desc, include.rownames = TRUE, caption.placement="top")

desc <- summary(df.steps) #from the psych library
desc <- xtable(desc, caption="Summary Statistics for Data", 
               label="Description Xtable", digits=1)
print(desc, include.rownames = TRUE, caption.placement="top")
##% latex table generated in R 3.1.2 by xtable 1.7-4 package
##% Fri Feb 13 14:50:37 2015
##The summary function displayed the median and the mean values.

## What is the average daily activity pattern?

df.averages <- aggregate(x=list(steps=df$steps), by=list(interval=df$interval), FUN=mean)
ggplot(data=df.averages, aes(x=interval, y=steps)) + geom_line() + 
  xlab("Intervals set at 5 minutes") + ylab("Average of steps taken")

df.averages[which.max(df.averages$steps),]
## Displayed 
##  interval    steps
##     104      835 206.1698


## Imputing missing values
df.missing <- is.na(df$steps)
num.missing <- sum(df.missing)
table(df.missing)

##Displayed
##df.missing
##FALSE 
##15264

table (num.missing)
## Displayed
##num.missing
##0 
#1

nafiller <- function(steps, interval){
  filler <- NA
  if (!is.na(steps))
    filler <- c(steps)
  else
    filler <- (df.averages[df.averages$interval==interval, "steps"])
  return(filler)
}
myfill.df <- df
myfill.df$steps <- mapply(nafiller, myfill.df$steps, myfill.df$interval)
head(myfill.df)

## Result got:
##  steps       date interval
##289     0 2012-10-02        0
##290     0 2012-10-02        5
##291     0 2012-10-02       10
##292     0 2012-10-02       15
##293     0 2012-10-02       20
##294     0 2012-10-02       25


##Make a histogram of the total number of steps taken each day and Calculate and report the mean and median ##total number of steps taken per day. Do these values differ from the estimates from the first part of the ##assignment? What is the impact of imputing missing data on the estimates of the total daily number of ##steps?

fill_steps_per_day <- aggregate(steps ~ date, rdata_fill, sum)
colnames(fill_steps_per_day) <- c("date","steps")

##plotting the histogram
ggplot(fill_steps_per_day, aes(x = steps)) + 
       geom_histogram(fill = "blue", binwidth = 1000) + 
        labs(title="Histogram of Steps Taken per Day", 
             x = "Number of Steps per Day", y = "Number of times in a day(Count)") + theme_bw() 